### ISSUE TITLE
Feature Request - add to xiloader

### ISSUE THREAD

**Issue by Hokuten85** [Shirk/XIPivot#1]
I didn't know of a better way to get a hold of the person maintaining this project. I was thinking of ways that we could possibly improve on the DAT switching capabilities while using windower and I started looking into modifying xiloader, which is a tool for getting on private servers.  I'm pretty terrible at c++, but I managed to hack together some of your stuff and xiloader and somehow managed to get it to work.
https://github.com/Hokuten85/xiloader

I didn't know if you wanted to put some time into a more elegant solution. I'll probably drop a similar request over on the darkstar/xiloader repo to see if they could add the functionality to the base product. Might be cool if you both collaborated.

**Comment by PoPoWanObi** [comment]
Hey @Hokuten85 

I'm interested in using this; but can't seem to figure out your folder structure for loading the ROMS folders.

I've got the xiloader compiled and running --xipivot in the args, but can't seem to actually load the dats.

Also, does this method allow replacing the UI and maps that were incompatible with the addon methods, since this is running at boot?

Thanks.

Edit: Figured it out. Sorry.

Files go in DATS\ROMS for anyone else who tries this and does not appear to replace the other files that had issues.

**Comment by Hokuten85** [comment]
Yeah, I got super hacky with what I did since it was mostly just for me. I put the DATS structure in the same folder as the xiloader.exe.

I believe it should load up the DATS sooner than the addon methods and it worked for everything that I tried, but I didn't really test comprehensively.

**Comment by PoPoWanObi** [comment]
I tried loading XI-Vision and XI-View and it doesn't appear to replace the originals prior to it loading in the game engine; which I find interesting because the console pops up and finishes long before the client opens.

Or perhaps I've got the folder structure messed up somehow which is possible. Either way, I much prefer this method over the addons so thanks for doing it anyway-- Ashita works well enough for loading XIPivot but Windower has been resetting the configuration file every boot, so it's been quite a pain to handle but with it being setup and run via XILoader it's been quite comforting.

Edit: Yup! Folder structure messed up, whoops. It appears to be loading the files no problem now, thanks! 👍

**Comment by HealsCodes** [comment]
Hi, sorry for not replying earlier.. I've been on a kind of hiatus for a bit..

If you're still interested @Hokuten85 then give me a poke - I should be receiving notifications again.

**Comment by Hokuten85** [comment]
@Shirk no worries. I've actually stopped playing, so don't go out of your way to implement this for me, only if you think its something other people might want.

**Comment by HealsCodes** [comment]
I would absolutely have done it back in November if I had noticed the issue earlier so I will keep it on my list for now.
