### ISSUE TITLE
(QoL) Request: Remove writing root_path to settings ini if std::filesystem::current_path() exists

### ISSUE THREAD

**Issue by twothreeforme** [Shirk/XIPivot#13]
This is a quality of life request... 

(I am using Ashita v4) I use a cloud to store all my settings/config files for the game so they are available on different computers. When I remove the "root_path" variable from the ini file, then: 
AshitaInterface.cpp line 289: `rootPath = std::filesystem::current_path() / "DATs";`
works fine to find the DATs, but:
AshitaInterface.cpp line 361: `config->SetValue(PluginName, "settings", "root_path", rootPath.string().c_str());`
saves this location in the settings file. I run this off two different computers, and the installation directories are different on each computer. So this setup will work on one computer, but when I swap to the other then I have to delete `root_path` from the ini and reload the game for the settings file to find my DATs again. 

Again, 
AshitaInterface.cpp line 289: `rootPath = std::filesystem::current_path() / "DATs";`
works fine to find my DATs folders because I haven't moved them from the originally intended install directory. I'm requesting to have THAT line be the default root_path location, and REMOVE line 361 IF the DAT folder exists in `std::filesystem::current_path()`

Great work on this, much appreciated !

**Comment by HealsCodes** [comment]
The simple solution for your shared settings scenario would be to use `root_path` the way it is intended and put your DATs folder into cloud storage as well, then point `root_path` at that directory.

The statement *"I'm requesting to have THAT line be the default `root_path` location, and REMOVE line 361 IF the DAT folder exists in `std::filesystem::current_path()`"* is presently *always true* because pivot ships with a DATs folder in that location. 

I'm OK to add a check to verify `root_path` exists and if not use a default-fallback because there are people that use `root_path` to point to a shared folder of overlays that they use between different client installations.

Outside of that.. your scenario is sadly not supported by pivot - if you want to share configurations between multiple systems then you should also have the files they refer to shared as well or otherwise in the same location on all systems.

**Comment by twothreeforme** [comment]
Completely understand, and appreciated. Would you be able to check if root_path does not exist, then also just check the CURRENT folder to see if DATs already exists ? That way, if I delete the root_path line in settings, and just leave the default installation, the DATs folder is in the current folder already, and there is no need to rewrite root_path anyway.
