### ISSUE TITLE
Setting root path for Windower

### ISSUE THREAD

**Issue by cpirie** [Shirk/XIPivot#4]
Hey! I noticed we're able to change root path for overlays with the Ashita version, but not the Windower. Is this due to a Windower requirement? I play on multiple PC's and put Windower into OneDrive, but I'd hate to have to put the 10+gigs of overlays in there too!

**Comment by HealsCodes** [comment]
It didn't play nice with Windower's settings framework so it was removed in v0.3.1.

For Ashita `root_path` is only ever read from the config but never stored, for Windower that wasn't possible so people were left with a `root_path` in their config files they never put in there and which would break things if they ever relocated their Windower files to a different location since a set variable in the config file overrides any defaults - even ones which would be correct.

(That scenario happened to enough people to become an issue).

If you want to risk it you can grab the v0.4.3 release I published a few minutes ago and then replace the XIPivot.lua with the version from this [Zip archive](https://github.com/Shirk/XIPivot/files/6167177/XIPivot.zip)
