### ISSUE TITLE
XIPivot: Lua runtime error: XIPivot//libs/_XIPivot.dll

### ISSUE THREAD

**Issue by brigaeilan** [Shirk/XIPivot#5]
Hi!
Sorry to raise this again, but I have followed all the instructions in your README file and installed the MS Visual C++ Runtime 2010 as well.
The error is still coming up: The specified module could not be found.

Cheers
Briga@Carbuncle

**Comment by Deejay85** [comment]
I'm having similar problems here, and as best as I can tell, it's because XIPivot isn't being loaded for some reason. I already checked the basic stuff like making sure it's updated to the latest version for Windower 0.3.2. Below are the file directory and the relevant changes related to getting XIPivot to run.


G:\FFXI Mods\Windower\settings.xml

```<?xml version="1.0" encoding="utf-8"?>
<settings>
	<global>
		<overlays></overlays>
	</global>
  <autoload>
    <addon>AutoRA</addon>
    <addon>azureSets</addon>
    <addon>boxdestroyer</addon>
etc.
```

G:\FFXI Mods\Windower\addons\XIPivot\data\Settings.xml

```
<?xml version="1.1" ?>
<settings>
    <global>
        <overlays>XI-View,AshenbubsHD-Basic,Maps</overlays>
    </global>
</settings>
```

G:\FFXI Mods\Windower\scripts\Init.txt

```
NEXTGames Edits:
// du blinking all all on
lua load XIPivot
Pivot a XI-View
Pivot a AshenbubsHD-Basic
Pivot a Maps
// Pivot a FFXI-XD
// lua load PartyBuffs
// lua load parse
// lua load skillchains
// sb visible
// statustimer setposy 78
// equipviewer pos 1650 748
// equipviewer pos 2192 990
// wait 30
// lua load GearInfo
config FrameRateDivisor 1
```

As you can see everything is as it should be, so I'm not sure what is going on here.

**Comment by asherthedragon** [comment]
Hello, i keep encountering the following error: "XIPivot: Lua runtime error: XIPivot//libs/_XIPivot.dll': The specified module could not be found."  I do have the Dll file inside of C:\Program Files (x86)\Windower4\addons\XIPivot\libs

**Comment by HealsCodes** [comment]
All of these are most likely due to the fact that you don't have (or have the wrong version of) the MSVC Runtime.

Pivot requires the **32bit MSVC 2010 runtime** - not the 64bit version, FFXI is a 32bit game.

**Comment by HealsCodes** [comment]
Marking this as closed with the changes made to the documentation in #8
